### ISSUE TITLE
Filesystem mount auth can be bypassed by use of symlinks

### ISSUE THREAD

**Issue by brettgeer** [open-policy-agent/opa-docker-authz#10]
docker run --rm -it -v "/:/test" --name...
docker: Error response from daemon: authorization denied by plugin opa-docker-authz: request rejected by administrative policy.

ln -s / volume
docker run --rm -it -v `pwd`/volume:/test ...

the root filesystem is now  availbale in the container

**Comment by tsandall** [comment]
@brettgeer thanks for opening this. I'm not sure if the authorization plugin can do anything about this as I suspect it would need to be able to stat the file (the webhook call probably receives the symlink path).

That being said, do you think this is valid given that the user needs host-level access in the first place to create the symlink?

**Comment by brettgeer** [comment]
Hi, testing for the path being a directory is a must, otherwise we'd just bypass auth using a symlink like I did

**Comment by tsandall** [comment]
I will follow up with Docker about this. I think the right solution is for Docker to resolve the symlinks before calling the webhook (possibly supplying both sets of paths) as every single plugin will need to do this.

**Comment by brettgeer** [comment]
Hi Torin,


   agreed, there are in fact cases when a symlink would be used, I can think of several I may use in future


brett

________________________________

**Comment by justincormack** [comment]
I am not sure that resolving the symlinks is necessarily the right solution, but maybe it helps (not sure I can see downsides but it may not be that useful). There are bind mounts to consider too (although those need more privileges in general), which cannot be resolved, and all sorts of other files, eg you can also bind `/` via `docker run --rm -it -v "/proc/self/root/:/test" alpine ls /test` and all sorts of other paths. So restricting file access by name alone is quite difficult.

**Comment by justincormack** [comment]
See my more detailed reply on https://github.com/moby/moby/issues/36020#issuecomment-357970248

**Comment by tsandall** [comment]
@justincormack posted a good set of recommendations for securing access to host-level directories (which applies to all authorization plugins) here: https://github.com/moby/moby/issues/36020#issuecomment-357970248. I don't think there's anything else to do on this ticket. Closing for now.

@brettgeer hope this helps. If there's something else we can help with, let us know.
