### ISSUE TITLE
arguments dropped in 0.2 and 0.2.1

### ISSUE THREAD

**Issue by animale66** [open-policy-agent/opa-docker-authz#14]
Hello, 

Thanks for contributing to the open source community.  I was noticing the following flags were dropped in the 0.2 and 0.2.1 release of opa-docker-authz, but were present in 1.6

  -bind-addr string
        sets the address the plugin will bind to (default ":8080")
  -opa-url string
        sets the base URL of OPA's HTTP API (default "http://localhost:8181/v1")

These two options enable me to run opa-docker-authz as a system daemon (along with the opa server 0.7.1).  

Normally, I'd run in a container, but I'm pushing for a fairly hardened version of docker, and my goal was to run opa-docker-authz outside of a container.  The containerized version on dockerhub fails in my environment because I leverage features like docker namespaces (examples of the failure below).  If the flags could be added back, then it'd be great. 

If not, could you perhaps comment as to why they were pulled? 

[root@tnv-it-ldockerdemo01 opa]# cat /etc/subuid
dockremap:1000000000:1300000000
[root@tnv-it-ldockerdemo01 opa]# cat /etc/subgid
dockremap:1000000000:1300000000
[root@tnv-it-ldockerdemo01 opa]#

docker: Error response from daemon: oci runtime error: container_linux.go:262: starting container process caused "process_linux.go:339: container init caused \"rootfs_linux.go:57: mounting \\\"/opt/app/opa/policy\\\" to rootfs \\\"/opt/data/docker/1000000000.1000000000/devicemapper/mnt/d9b8329c287665c62557c6d14accd1281827e30e4dc5bfb7345cc21e8a349eec/rootfs\\\" at \\\"/policies\\\" caused \\\"stat /opt/app/opa/policy: permission denied\\\"\"".

**Comment by animale66** [comment]
That makes sense - I managed to get the binary to launch.  Seems I just needed to clean out the old /var/run/docker/plugins/*.sock object from the old version for some reason and it launches. 

Related to the available switches though, I am having issues with the sample 'example.rego' file provided in this repo, so I suspect there's been some syntax changes with OPA since it's been provided.  Perhaps, when opa-docker-authz starts we could get the output of of **./opa check** or provide the -check flag to confirm it? 

An update to example.rego would be beneficial too.


This is the opa v0.7.1 release linux_amd64 binary

**[root@tnv-it-ldockerdemo01 bin]# ./opa check ../policy/example_github.rego**
1 error occurred during loading: 1 error occurred: ../policy/example_github.rego:20: rego_parse_error: no match found, expected: "!=", "#", "&", "(", "*", "+", "-", ".", "/", "0", ";", "<", "<=", "==", ">", ">=", "[", "\"", "`", "default", "false", "import", "not", "null", "package", "set(", "true", "with", "{", "|", [ \t\r\n], [ \t], [1-9], [A-Za-z_] or EOF
**[root@tnv-it-ldockerdemo01 bin]# ./opa-docker-authz -policy-file /opt/app/opa/policy/example_github.rego**
2018/03/08 22:56:00 Starting server.
2018/03/08 22:56:03 Querying OPA policy data.docker.authz.allow. Input: {
  "AuthMethod": "",
  "Body": null,
  "Headers": {
    "User-Agent": "Docker-Client/17.06.2-ol (linux)"
  },
  "Method": "GET",
  "Path": "/_ping",
  "User": ""
}

I get similar failures after trying docker with it.  
2018/03/08 22:56:03 Returning OPA policy decision: false (error: 1 error occurred: 1 error occurred: /opt/app/opa/policy/example_github.rego:20: rego_parse_error: no match found, expected: "#", "&", "*", "+", "-", ".", "/", "0", ";", "[", "\"", "`", "default", "false", "import", "not", "null", "package", "set(", "true", "with", "{", "|", [ \t\r\n], [ \t], [1-9], [A-Za-z_] or EOF)




If you are curious:

RPM:
docker-engine-17.06.2.ol-1.0.1.el7.x86_64
OracleLinux 7.4 x86_64

[root@tnv-it-ldockerdemo01 bin]# docker info
Containers: 5
 Running: 0
 Paused: 0
 Stopped: 5
Images: 3
Server Version: 17.06.2-ol
Storage Driver: devicemapper
 Pool Name: docker-253:3-100824054-pool
 Pool Blocksize: 65.54kB
 Base Device Size: 10.74GB
 Backing Filesystem: xfs
 Data file: /dev/loop0
 Metadata file: /dev/loop1
 Data Space Used: 823.7MB
 Data Space Total: 107.4GB
 Data Space Available: 31.37GB
 Metadata Space Used: 1.884MB
 Metadata Space Total: 2.147GB
 Metadata Space Available: 2.146GB
 Thin Pool Minimum Free Space: 10.74GB
 Udev Sync Supported: true
 Deferred Removal Enabled: false
 Deferred Deletion Enabled: false
 Deferred Deleted Device Count: 0
 Data loop file: /opt/data/docker/1000000000.1000000000/devicemapper/devicemapper/data
 Metadata loop file: /opt/data/docker/1000000000.1000000000/devicemapper/devicemapper/metadata
 Library Version: 1.02.140-RHEL7 (2017-05-03)
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 6e23458c129b551d5c9871e5174f6b1b7f6d1170
runc version: 810190ceaa507aa2727d7ae6f4790c76ec150bd2
init version: 949e6fa
Security Options:
 seccomp
  Profile: default
 userns
Kernel Version: 3.10.0-693.17.1.el7.x86_64
Operating System: Oracle Linux Server 7.4
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 3.702GiB
Name: tnv-it-ldockerdemo01.dev.msci.org
ID: 4ISG:VONF:3ALH:PL5E:GT4U:LOES:CDEZ:2IJ4:G2O4:EYSQ:2RGX:AJVZ
Docker Root Dir: /opt/data/docker/1000000000.1000000000
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

WARNING: devicemapper: usage of loopback devices is strongly discouraged for production use.
         Use `--storage-opt dm.thinpooldev` to specify a custom block storage device.
WARNING: bridge-nf-call-iptables is disabled
WARNING: bridge-nf-call-ip6tables is disabled

**Comment by tsandall** [comment]
The example.rego is quite out of date. I'll submit a PR and fix that.

**Comment by tsandall** [comment]
If you'd like, feel free to submit a PR to add a `-check` flag. You can implement the behaviour as follows:

1. if -check flag is set...
2. read file into memory
3. parse file using `ast.ParseModule` function (from OPA)
4. compile using `ast.Compiler` (from OPA)

Here's an example of how to do this: https://godoc.org/github.com/open-policy-agent/opa/ast#example-Compiler-Compile

Hope this helps!
