### ISSUE TITLE
need help on the rego file

### ISSUE THREAD

**Issue by CharanBR** [open-policy-agent/opa-docker-authz#18]
each rule below works independently but when I put all of them in deny, opa allows all of them.

package docker.authz

default allow = false
allow {
    not deny
}

deny {
   privileged
   seccomp_unconfied
   usens_disable
}

privileged {
    input.Body.HostConfig.Privileged = true
}

seccomp_unconfied {
    input.Body.HostConfig.SecurityOpt[_] = "seccomp:unconfined"
}

usens_disable {
    input.Body.HostConfig.UsernsMode = "host"
}

**Comment by tsandall** [comment]
Statements in the body of a rule are ANDed together which means your deny rule reads as follows:

`deny IF privileged AND seccomp_unconfined AND usens_disable`.

What I think you want to say is `deny IF privileged OR seccomp_unconfined OR usens_disable`.

You can express this as follows:

```
allow { not deny }

deny { privileged }
deny { seccomp_unconfined }
deny { usens_disable }
```

Rules with the same name are ORed together.

**Comment by CharanBR** [comment]
gotcha ! thank you.
