### ISSUE TITLE
Docker Hub Image for 0.2.2

### ISSUE THREAD

**Issue by nbrownuk** [open-policy-agent/opa-docker-authz#21]
Do you plan on pushing an image based on 0.2.2, to the openpolicyagent/opa-docker-authz Docker Hub repo? Thanks.

**Comment by tsandall** [comment]
hi @nbrownuk, sorry for the delay. We've been busy with KubeCon EU this week. We'll get the Docker Hub repo updated.

**Comment by nbrownuk** [comment]
Thanks @tsandall
