### ISSUE TITLE
run authorization plugin

### ISSUE THREAD

**Issue by alobaidan** [open-policy-agent/opa-docker-authz#22]
Hi,

what are the differences between runs the authorization plugin directly on the host or inside a container ?

Many thanks.

Ibrahim

**Comment by tsandall** [comment]
Running the plugin as a container means you don't have to install any host-level packages. If you're trying to keep your host installation as minimal as possible, running the plugin as a container will help.

Keep in mind that if the plugin container stops, Docker will not be accessible--you'll need host-level access to restart the plugin container. You should make sure that you configure the plugin container's restart policy to be Always. You may also want to include a rule in the policy to prevent users from stopping the plugin container. I haven't done this myself, but it should be possible.

Hope this helps. Feel free to re-open this or file other issues if you have more questions.
