### ISSUE TITLE
Docker authorzation plugin

### ISSUE THREAD

**Issue by alobaidan** [open-policy-agent/opa-docker-authz#28]
Hi,

I would like to create docker authorization plugin. but I have problem with the socket because docker socket cannot identify the user.

Is there anyway to make the socket identify the user ?

for example 
the request send to the docker daemon have (subject, object and action).

Many thanks

**Comment by tsandall** [comment]
@alobaidan I don't think there's anything to do on the OPA/plugin side. This is more a question of what Docker supports in terms of authentication. See the Docker documentation for more info: https://docs.docker.com/engine/extend/plugins_authorization/

It looks like you can configure TLS on the socket. If you do that, there will be user context included in the `input` document.

**Comment by KajdeMunter** [comment]
For anyone stumbling on this through Google, I use Traefik and have configured it to use the Docker Socket through TLS. Dockers documentation will tell you the value of `User` is set to the client certificate subject common name. In my case the value was `Client`. 

```rego
package docker.authz

default allow = false

allow = true {
    input.User == "client"
}
```
Will evaluate to True when using Traefik. `journalctl -f -u docker.service` will show you all available fields.
