### ISSUE TITLE
What policy to enforce --user in docker run

### ISSUE THREAD

**Issue by przemolb** [open-policy-agent/opa-docker-authz#30]
Hi,
I am trying to enforce our users to run `docker run` with `--user` parameter.
Have looked at the documentation but couldn't find any close example.
Can anybody tell me how could I achieve it ?

**Comment by tsandall** [comment]
@przemolb you'll need to look at the plugin logs to figure out how Docker represents the --user parameter in the API request to be authorized. Each time the plugin queries OPA, it logs the input values provided.
