### ISSUE TITLE
Docker images are hosed on docker hub

### ISSUE THREAD

**Issue by zackpay** [open-policy-agent/opa-docker-authz#38]
The docker images hosted on docker hub show a size of 0 bytes and I'm unable to pull any of the images.

**Comment by ashutosh-narkar** [comment]
@zackpay are you following instructions as described [here](https://www.openpolicyagent.org/docs/latest/docker-authorization/) ? I was able to install the plugin.

More installation instructions [here](https://github.com/open-policy-agent/opa-docker-authz#install).

**Comment by anderseknert** [comment]
Seems to work from here too. Closing for now and can re-open if needed.
