### ISSUE TITLE
Empty User value,  log as level=error msg="  \"User\": \"docker.client\"" 

### ISSUE THREAD

**Issue by prudhvigodithi** [open-policy-agent/opa-docker-authz#39]
Hey I'm trying to run this OPA plugin inside Debian host which is Kubernetes worker node (setup used is kops for Kubernetes), I see that in docker logs User is an empty string, not able to get the user information, whereas I get all other input values like Headers, Path, method, Body, AuthMethod, so when I try to write rego auth policy with the User information it's failing as the User string is empty, this Works when I try to run with header Authz-user and able to identify this header and works in restricting policy based on Authz-user, but I'm trying to set up dynamically to identify the authz policy based on "User" value is failing as the User value is empty, is this know issue?, or please suggest me If i'm doing something wrong.

After I have added on the print logs  got the following information 

```
level=info msg="map[Headers:map[User-Agent:Go-http-client/1.1] Path:/v1.38/containers/json?filters=%7B%22label%22%3A%7B%22io.kubernetes.docker.type%3Dpodsandbox%22%3Atrue%7D%7D&limit=0 Method:GET Body:<nil> User: AuthMethod:]" plugin=09471751e6c6377f84ce177fcc1180baa75ca719a41940611a3beaf9f3c75da8

Mar 19 17:36:36 ip-10-35-6-100 dockerd[3725]: time="2020-03-19T17:36:36-04:00" level=error msg="    \"User-Agent\": \"Go-http-client/1.1\"" plugin=009471751e6c6377f84ce177fcc1180baa75ca719a41940611a3beaf9f3c75da8

Mar 19 17:36:36 ip-10-35-6-100 dockerd[3725]: time="2020-03-19T17:36:36-04:00" level=error msg="  \"User\": \"\"" plugin=09471751e6c6377f84ce177fcc1180baa75ca719a41940611a3beaf9f3c75da8

level=info msg="map[AuthMethod: Headers:map[User-Agent:Go-http-client/1.1] Path:/v1.38/containers/json?all=1&filters=%7B%22label%22%3A%7B%22io.kubernetes.docker.type%3Dcontainer%22%3Atrue%7D%2C%22status%22%3A%7B%22running%22%3Atrue%7D%7D&limit=0 Method:GET Body:<nil> User:]" plugin=09471751e6c6377f84ce177fcc1180baa75ca719a41940611a3beaf9f3c75da8
```

In the above log the user information is empty
```
\"User\": 
 User:]
```

**Comment by tsandall** [comment]
@prudhvigodithi I'm not surprised that calls to the docker daemon are unauthenticated. I'd recommend investigating Kubernetes admission control to figure out if your policy can be implemented at that layer instead of inside the container runtime. See the Kubernetes admission control docs on openpolicyagent.org for more info.

**Comment by prudhvigodithi** [comment]
got it thanks, but our operations include a direct talk with the docker daemon, currently is there a way I can restrict Authz-User form complete docker run which includes

```
docker run 
docker run -it -d --name <> <image_name>
docker run <image_name>
```

As i see when I restricted with 
```
deny {
    input.Headers["Authz-User"] == "test"
    containers_run
}
containers_run { 
  contains(input.Path, "/create")
}
```

This is even stopping the image form pulling also, I want to stop it only from docker run whereas a user can do a docker pull. if this gets done I guess I need not go to k8s admission control, as suggestions on how to allow docker pull and stop docker run ?

**Comment by prudhvigodithi** [comment]
Hey thanks a lot for reaching me back, our operations involve direct querying of docker daemon so at this point we cannot go to Kubernetes admission control though our setup is in Kubernetes, however at this point, I was wondering if we have some webhook actions based on docker queries like if a command executed like a docker run --net as host to trigger an email or notification, in that case, we need to move to Kubernetes admission control as we get notifications based on docker.client user, any suggestions on how can I do this, currently we are allowing docker run commands only if the container name starts with a particular repo name, can we get notified when this gets triggered? please let me know.

```
allow {
    input.Headers["Authz-User"] == "test"
    image_run
}

image_run {
   contains(input.Path ,"/")
   startswith(input.Body.Image, "docker.privaterepo.aws/devops/")
}

```

Can we get notified when this gets triggered ?

**Comment by tsandall** [comment]
OPA lets you execute policies. It doesn't support scanning of resources and triggering out-of-the-box. You would have to build that yourself. This plugin also doesn't do it for you--it just integrates OPA with Docker to enforce authorization policies.
