### ISSUE TITLE
Add support for returning details about why a request was rejected by policy

### ISSUE THREAD

**Issue by atoom** [open-policy-agent/opa-docker-authz#44]
Hi,

We have implemented quite a lot of policy rules according to the CIS Benchmark for Docker and it works great. Unfortunately it is very difficult for the end user to understand in what way they might violate certain policies as the error message is hardcoded to `request rejected by administrative policy`.

Would it be possible to add support for customizing the error message that is returned to the end user ?

**Comment by tsandall** [comment]
@atoom the plugin expects the policy to return a boolean indicating whether the request should be allowed or not: https://github.com/open-policy-agent/opa-docker-authz/blob/master/main.go#L94

If you wanted, you could extend the plugin to receive an object that indicates (a) whether to allow/deny the request and (b) if the request is denied, a reason. Something like:

```json
```

**Comment by atoom** [comment]
@tsandall Thanks for the input!

Do you think this is a feature that would be beneficial for others - i.e. would you accept a PR or is it better if we fork the plugin code and maintain it internally only for us ?

**Comment by atoom** [comment]
We will do this internally first and if we feel it is good enough we will open a PR for you to consider!

**Comment by tsandall** [comment]
OK @atoom sorry for the delayed responses. This repo is somewhat lower priority since it has fewer users than other OPA integrations like ones for Kubernetes, Envoy, etc. If you'd like to contribute improvements, please just file an issue ahead of time outlining the functionality.
