### ISSUE TITLE
Release v0.6

### ISSUE THREAD

**Issue by thomasco** [open-policy-agent/opa-docker-authz#45]
@tsandall, can you cut a release for v0.6? I'm not sure what exactly is required to make `docker plugin install` work – maybe also updating Docker Hub?

**Comment by tsandall** [comment]
@thomasco I've pushed the v0.6 version to Docker Hub. I haven't tested the install so please let me know if it works.

**Comment by thomasco** [comment]
I installed it and briefly tested things out – everything seems to work. Thanks!
