### ISSUE TITLE
Is there a way matching data of body to patterned string ?

### ISSUE THREAD

**Issue by keyolk** [open-policy-agent/opa-docker-authz#5]
Hi,
I'm trying to force user to use white/black listed volume binding.
But I cant find how I can match it to some patterned string, like regex expression. 

```
valid_volume_mapping {
  input.Body.HostConfig.Binds[_] = ????
} 
```
for example what I want to is ..
allow belows
-v /allowed/:/one -> o
-v /allowed/:/two -> o
-v /allowed/:/three -> o

and deny belows
-v /:/one -> x
-v /:/two -> x
-v /:/three -> ...

any Ideas to solve ?

**Comment by tsandall** [comment]
OPA supports a bunch of string manipulation built-ins as well as regex matching: http://www.openpolicyagent.org/docs/language-reference.html

Something like...

```
valid_volume_mapping_whitelist = true {
    invalid_paths = host_volume_paths - valid_host_paths
    count(invalid_paths, 0)
}

valid_volume_mapping_blacklist = true {
    invalid_paths = host_volume_paths & invalid_host_paths
    count(invalid_paths, 0)
}

host_volume_paths[trimmed] {
    input.Body.HostConfig.Binds[_] = bind
    split(bind, ":", parts)
    trim(parts[0], "/", trimmed)
}

valid_host_paths = {"allowed", "also/allowed"}
invalid_host_paths = {"forbidden", "also/forbidden"}
```

Does this solve your issue?

**Comment by keyolk** [comment]
@tsandall Super! it works exactly what I want : D
and ... last
From log,
it puts decimalized body data to output
Is there a way to convert it to string ?

Currently what I see is like below
```
Received request from Docker: {  POST /v1.31/containers/create [123 34 72 111 115 116 110 97 109 101 34 58 34 34 44 34 68 111 109 97 105 110 110 97 109 101 34 58 34 34 44 34 85 115 101 114 34 58 34 34 44 34 65 116 116 97 99 104 83 116 100 105 110 34 58 116 114 117 101 44 34 65 116 116 97 99 104 83 116 100 111 117 116 34 58 116 114 117 101 44 34 65 116 116 97 99 104 83 116 100 101 114 114 34 58 116 114 117 101 44 34 84 116 121 34 58 116 114 117 101 44 34 79 112 101 110 83 116 100 105 110 34 58 116 114 117 101 44 34 83 116 100 105 110 79 110 99 101 34 58 116 114 117 101 44 34 69 110 118 34 58 91 93 44 34 67 109 100 34 58 91 34 115 104 34 93 44 34 73 109 97 103 101 34 58 34 98 117 115 121 98 111 120 34 44 34 86 111 108 117 109 101 115 34 58 123 125 44 34 87 111 114 107 105 110 103 68 105 114 34 58 34 34 44 34 69 110 116 114 121 112 111 105 110 116 34 58 110 117 108 108 44 34 79 110 66 117 105 108 100 34 58 110 117 108 108 44 34 76 97 98 101 108 115 34 58 123 125 44 34 72 111 115 116 67 111 110 102 105 103 34 58 123 34 66 105 110 100 115 34 58 91 34 47 117 115 114 58 47 104 111 115 116 34 93 44 34 67 111 110 116 97 105 110 101 114 73 68 70 105 108 101 34 58 34 34 44 34 76 111 103 67 111 110 102 105 103 34 58 123 34 84 121 112 101 34 58 34 34 44 34 67 111 110 102 105 103 34 58 123 125 125 44 34 78 101 116 119 111 114 107 77 111 100 101 34 58 34 100 101 102 97 117 108 116 34 44 34 80 111 114 116 66 105 110 100 105 110 103 115 34 58 123 125 44 34 82 101 115 116 97 114 116 80 111 108 105 99 121 34 58 123 34 78 97 109 101 34 58 34 110 111 34 44 34 77 97 120 105 109 117 109 82 101 116 114 121 67 111 117 110 116 34 58 48 125 44 34 65 117 116 111 82 101 109 111 118 101 34 58 116 114 117 101 44 34 86 111 108 117 109 101 68 114 105 118 101 114 34 58 34 34 44 34 86 111 108 117 109 101 115 70 114 111 109 34 58 110 117 108 108 44 34 67 97 112 65 100 100 34 58 110 117 108 108 44 34 67 97 112 68 114 111 112 34 58 110 117 108 108 44 34 68 110 115 34 58 91 93 44 34 68 110 115 79 112 116 105 111 110 115 34 58 91 93 44 34 68 110 115 83 101 97 114 99 104 34 58 91 93 44 34 69 120 116 114 97 72 111 115 116 115 34 58 110 117 108 108 44 34 71 114 111 117 112 65 100 100 34 58 110 117 108 108 44 34 73 112 99 77 111 100 101 34 58 34 34 44 34 67 103 114 111 117 112 34 58 34 34 44 34 76 105 110 107 115 34 58 110 117 108 108 44 34 79 111 109 83 99 111 114 101 65 100 106 34 58 48 44 34 80 105 100 77 111 100 101 34 58 34 34 44 34 80 114 105 118 105 108 101 103 101 100 34 58 102 97 108 115 101 44 34 80 117 98 108 105 115 104 65 108 108 80 111 114 116 115 34 58 102 97 108 115 101 44 34 82 101 97 100 111 110 108 121 82 111 111 116 102 115 34 58 102 97 108 115 101 44 34 83 101 99 117 114 105 116 121 79 112 116 34 58 110 117 108 108 44 34 85 84 83 77 111 100 101 34 58 34 34 44 34 85 115 101 114 110 115 77 111 100 101 34 58 34 34 44 34 83 104 109 83 105 122 101 34 58 48 44 34 67 111 110 115 111 108 101 83 105 122 101 34 58 91 48 44 48 93 44 34 73 115 111 108 97 116 105 111 110 34 58 34 34 44 34 67 112 117 83 104 97 114 101 115 34 58 48 44 34 77 101 109 111 114 121 34 58 48 44 34 78 97 110 111 67 112 117 115 34 58 48 44 34 67 103 114 111 117 112 80 97 114 101 110 116 34 58 34 34 44 34 66 108 107 105 111 87 101 105 103 104 116 34 58 48 44 34 66 108 107 105 111 87 101 105 103 104 116 68 101 118 105 99 101 34 58 91 93 44 34 66 108 107 105 111 68 101 118 105 99 101 82 101 97 100 66 112 115 34 58 110 117 108 108 44 34 66 108 107 105 111 68 101 118 105 99 101 87 114 105 116 101 66 112 115 34 58 110 117 108 108 44 34 66 108 107 105 111 68 101 118 105 99 101 82 101 97 100 73 79 112 115 34 58 110 117 108 108 44 34 66 108 107 105 111 68 101 118 105 99 101 87 114 105 116 101 73 79 112 115 34 58 110 117 108 108 44 34 67 112 117 80 101 114 105 111 100 34 58 48 44 34 67 112 117 81 117 111 116 97 34 58 48 44 34 67 112 117 82 101 97 108 116 105 109 101 80 101 114 105 111 100 34 58 48 44 34 67 112 117 82 101 97 108 116 105 109 101 82 117 110 116 105 109 101 34 58 48 44 34 67 112 117 115 101 116 67 112 117 115 34 58 34 34 44 34 67 112 117 115 101 116 77 101 109 115 34 58 34 34 44 34 68 101 118 105 99 101 115 34 58 91 93 44 34 68 101 118 105 99 101 67 103 114 111 117 112 82 117 108 101 115 34 58 110 117 108 108 44 34 68 105 115 107 81 117 111 116 97 34 58 48 44 34 75 101 114 110 101 108 77 101 109 111 114 121 34 58 48 44 34 77 101 109 111 114 121 82 101 115 101 114 118 97 116 105 111 110 34 58 48 44 34 77 101 109 111 114 121 83 119 97 112 34 58 48 44 34 77 101 109 111 114 121 83 119 97 112 112 105 110 101 115 115 34 58 45 49 44 34 79 111 109 75 105 108 108 68 105 115 97 98 108 101 34 58 102 97 108 115 101 44 34 80 105 100 115 76 105 109 105 116 34 58 48 44 34 85 108 105 109 105 116 115 34 58 110 117 108 108 44 34 67 112 117 67 111 117 110 116 34 58 48 44 34 67 112 117 80 101 114 99 101 110 116 34 58 48 44 34 73 79 77 97 120 105 109 117 109 73 79 112 115 34 58 48 44 34 73 79 77 97 120 105 109 117 109 66 97 110 100 119 105 100 116 104 34 58 48 125 44 34 78 101 116 119 111 114 107 105 110 103 67 111 110 102 105 103 34 58 123 34 69 110 100 112 111 105 110 116 115 67 111 110 102 105 103 34 58 123 125 125 125 10] map[Content-Length:1433 Content-Type:application/json User-Agent:Docker-Client/17.07.0-ce (linux) Authz-User:alice] [] 0 [] map[]}

```

**Comment by keyolk** [comment]
@tsandall 
Sorry, one more question.

Lets say docker client try to create container with below volume binding. 
- case1 : /usr:/host/usr
- case2: /usr/lib:/host/usr/lib

and what my desired policy is that
never allow client to make binds under host's /usr path.

case1 is easily covered by your helpful example rego, thanks again.
but for case2, I stucked.

I tried write policy with builtin function startswith() 
but didn't make it.

Could you give me more advise ? 

and is there more .rego example to understand ?
too few example on my gooling  : (

**Comment by tsandall** [comment]
If you want to whitelist/blacklist prefixes, try something like...

```
valid_volume_mapping_whitelist {
    invalid_paths = host_volume_paths - valid_host_volume_paths
    count(invalid_paths, 0)
}

valid_volume_mapping_blacklist {
    invalid_paths = host_volume_paths & invalid_host_volume_paths
    count(invalid_paths, 0 )
}

valid_host_volume_paths[host_path] {
    host_volume_paths[host_path]
    startswith(host_path, valid_host_path_prefixes[_])
}

invalid_host_volume_paths[host_path] {
    host_volume_paths[host_path]
    startswith(host_path, invalid_host_path_prefixes[_])
}

host_volume_paths[trimmed] {
    input.Body.HostConfig.Binds[_] = bind
    split(bind, ":", parts)
    trim(parts[0], "/", trimmed)
}

valid_host_path_prefixes = {"allowed", "also/allowed"}
invalid_host_path_prefixes = {"forbidden", "also/forbidden"}
```

Regarding examples, you can find a bunch in the documentation and tutorials on the OPA website. 

Also, we're starting to populate a standard library in https://github.com/open-policy-agent/library. If you have Docker policies you'd like to contribute, please go ahead and submit a PR there!

**Comment by tsandall** [comment]
The logging could be improved by changing this: https://github.com/open-policy-agent/opa-docker-authz/blob/master/main.go#L36. Instead of just printing the request value, the code could reach into the request object and print individual values.

**Comment by keyolk** [comment]
@tsandall 
Kool : )

**Comment by tsandall** [comment]
Created an issue to track the request logging improvement. Closing this for now. Feel free to reopen if you feel like there are other related questions.

**Comment by HugoRh** [comment]
Hi,

I'm struggling like crazy with this one...
I use the below settings -
valid_host_paths = {"/allowed/path"}

host_volume_paths[trimmed] {
    input.Body.HostConfig.Binds[_] = bind
    split(bind, ":", parts)
    trim(parts[0], "/", trimmed)
}

valid_volume_mapping_whitelist = true {
    invalid_paths = host_volume_paths - valid_host_paths
    count(invalid_paths, 0)
}

allow {
valid_volume_mapping_whitelist = true
}

my goal here is to prevent the mount of a host directory regardless of the number of volume defined.
so below should work
docker run -ti -v  /allowed/path:/somepath --rm centos:7 bash
and this one should bounce
docker run -ti -v  /allowed/path:/somepath -v /notallowed:someotherpath --rm centos:7 bash

but whatever I try I get either all combination is working or all is bouncing...
Please help...

Thanks !!

**Comment by tsandall** [comment]
@HugoRh `valid_host_paths` contains `"/allowed/path"` but `host_volume_paths` is trimming the leading and trailing "/" characters from the host paths.

**Comment by HugoRh** [comment]
@tsandall  Thanks !
I'm was  struggling with the syntax...

Because this page appears on google search ( where the info is very limited on this topic), let me share my policy.rego (used to secure docker dev environments, so users can run containers locally but only with certains path on the host + all the options to limit authorization escalation), finally this policy is agnostic regarding docker api .

package docker.authz

default allow = false

#Allow any if the Authz-Token is a secured token
allow {
    input.Headers["Authz-Token"] = "[MY-SECURE-TOKEN]"
}

# Allow all GET requests
allow {
   input.Method = "GET"
}

#Allow all POST requests which are not container create
allow {
   input.Method = "POST"
   not contains(input.Path ,"/containers/create")
}

#Defining authorized mountpoints on host to be used as docker volume
valid_host_paths = {"/Some/allowed/path","/Some/other/allowed/path"}

host_volume_paths[parts[0]] {
    input.Body.HostConfig.Binds[_] = bind
    split(bind, ":", parts)
}

valid_volume_mapping_whitelist = true {
    invalid_paths = host_volume_paths - valid_host_paths
    count(invalid_paths, 0)
}

#Allow all POST requests which are container create with security sensitive feature disabled with or without a volume
allow {
   input.Method = "POST"
   contains(input.Path ,"/containers/create")
   input.Body.User = ""
   input.Body.HostConfig.PidMode = ""
   input.Body.HostConfig.UTSMode = ""
   input.Body.HostConfig.UsernsMode  = ""
   input.Body.HostConfig.Privileged = false
   is_null(input.Body.HostConfig.CapAdd)
   is_null(input.Body.HostConfig.CapDrop)
   is_null(input.Body.HostConfig.SecurityOpt)
   valid_volume_mapping_whitelist = true
}

**Comment by bviktor** [comment]
Thanks for all the pointers, unfortunately this only solves the `docker run -v /:/host-root` runs, not the `docker run --mount type=bind,source=/,target=/host-root` ones. The latter populates the `input.Body.HostConfig.Mounts[_].Source` (I think). Any suggestions how to solve that one?

---

Another question is, is there a macro for the current user's home dir? This is my current policy:

https://raw.githubusercontent.com/noobient/noobuntu/063a453f03d36d20fb0435646608d33d01bd74cb/ansible/roles/devenv/files/authz.rego

Currently I restrict binds to home, but that still allows people to browse other people's homes. It'd be great to use something like $HOME.

**Comment by bviktor** [comment]
I solved the first part with this setup:

https://github.com/noobient/noobuntu/blob/6d330b28b2e956492e346beda6bed32aa826ee55/ansible/roles/docker/files/authz.rego

Now the only question is about the home dir of the running user. Unfortunately I couldn't find any trace of either that or the username (from which I could construct the home dir) in `input.Body`...
