### ISSUE TITLE
How to reduce decision logging?

### ISSUE THREAD

**Issue by darrais** [open-policy-agent/opa-docker-authz#52]
Hi,

Is there is a way to reduce the amount of logs produced when calling the **opa-docker-authz** plugin?

I noticed that, for every **docker** command executed, the entire input HTTP request and the corresponding decision is logged with a logging level of **ERROR**. This seems (for lack of a better word) extreme. In my perspective, in no way is the information logged erratic of some sort.

I'd expect that, for a logging level of **ERROR**, only essential information would be logged. Logging of the entire HTTP input request seems more appropriate for a logging level of either **INFO** or **DEBUG**.

**Comment by tsandall** [comment]
Today we don't have any logging levels--the integration just prints log messages to stderr via the standard Go `log` package. Because of this, I'm not sure where the "ERROR" level you're referring to is coming from. It would be relatively easy to add an option to the integration to disable logging on each request (e.g., a `--quiet` flag or similar). We'd be happy to accept a PR for this.

**Comment by darrais** [comment]
Hi @tsandall,

I've already created a PR for this - please see https://github.com/open-policy-agent/opa-docker-authz/pull/53. Note that this was my first time coding in Go and fiddling around with Docker plugins at this level. I hope I've done everything as expected.

I've tried to keep changes to a minimum, and set the `-quiet` flag to disable only the logging of the HTTP requests. Every other message is still logged. If what you were actually suggesting was to disable every message, I believe a different approach would be better - to a have a function with the sole purpose of logging messages. That way, we'd need only to place the `-quiet` flag logic inside the function code, instead of on every `Print*` call.

Nonetheless, I think it's helpful to always log messages related with the plugin's final decision. Logging of the entire HTTP input request is what it seems to me more appropriate for debugging purposes only.

Thank you!
