### ISSUE TITLE
Restricting docker exec to specific users not working

### ISSUE THREAD

**Issue by josephlim75** [open-policy-agent/opa-docker-authz#58]
Running `opa_version : v0.18.0, plugin_version: 0.7`
## Policy file
```
package docker.authz

default allow = false

allow {
  input.Method = "POST"
  input.Body.User = "1001"
  # endswith(input.Headers.Path, "/exec")
}

allow {
  input.Method = "GET"
}
```

## Journal Log
```
{
  "config_hash":"343b6564c00433b4d8fcaf6c4f86fb293a49acc1dd73865463a99309a9765c20",
  "decision_id":"355ca233-275d-4f5e-a3e6-06444acabb83",
  "input":{
    "AuthMethod":"",
    "Body":{
      "AttachStderr":true,
      "AttachStdin":true,
      "AttachStdout":true,
      "Cmd":["sh"],
      "Detach":false,
      "DetachKeys":"","Env":null,
      "Privileged":false,"Tty":true,
      "User":"1001",
      "WorkingDir":""
    },
    "Headers":{
      "Content-Length":"176",
      "Content-Type":"application/json",
      "User-Agent":"Docker-Client/19.03.13 (linux)"},
      "Method":"POST",
      "Path":"/v1.40/containers/9d119071f178/exec",
      "User":""
    },
    "labels":{
      "app":"opa-docker-authz",
      "id":"816a2e17-38b0-4692-93f1-c44423b73f79",
      "opa_version":"v0.18.0",
      "plugin_version":"0.7"
    }
}
```
## Command Results
```
docker exec -it -u 1001 9d119071f178 sh
Error response from daemon: authorization denied by plugin opa-docker-authz:latest: request rejected by administrative policy
```

**Comment by anderseknert** [comment]
Thanks for reporting this @josephlim75. Could you add another allow rule for `HEAD` requests?

```
allow {
  input.Method == "HEAD"
}
```

The Docker command line client sends a ping request (`HEAD` to `/_ping`) to check that the server is up before it sends the "actual" request, and I suspect that's what's getting denied here.

Next release of the plugin will see this fixed, as we'll exclude the ping request from policy evaluation by default. The code is all there already, but there's some work left to be done on release automation which I had to leave before my vacation.

**Comment by josephlim75** [comment]
@anderseknert  Thanks.  I have added the `HEAD` method as you mentioned.  I got another error now.

```
$ docker exec -it -u 1001 9d119071f178 bash
unable to upgrade to tcp, received 403
```

**Comment by anderseknert** [comment]
Can't say I've seen that before. If OPA denied the request I would expect the usual "authorization denied by plugin opa-docker-authz" but still, might be useful to check the logs one extra time if there are more requests included in the "exec" action not currently covered by the policy? I take it the error is gone if you add something like:

```rego
allow {
    true
}
```

..right? The Docker CLI is a little tricky, as many of the commands result in multiple API calls, and it's not always obvious which ones without checking the logs.

**Comment by josephlim75** [comment]
I finally got it working but still having some issue, hope if you have a solution to my problem.  When i issue `docker exec -it -u 1001 <container> bash`, there are 3 requests  send to Docker namely, `/exec`, `/resize` and `/start`.  For the arguments I needed for my decisioning, it is all located in request `/exec`, After `/exec`, another request `/resize` and `/start` is send.  For now I have the following, but that defeat the purpose of my `/exec`.  If I want to deny, i couldn't because the following `/resize` and `/start` is always true.  Is there a way to chain them together ?
```
allow {
  contains(input.Path, "resize")
}

allow {
  endswith(input.Path, "start")
}
```

**Comment by josephlim75** [comment]
Ignore my previous comment, I think i manage to make it work now.  At least I can restrict `docker exec` with a non-root user
```
package docker.authz


default allow = false

allow {
  input.Method = "POST"
  input.Body.User != "0"
  input.Body.User != ""
  input.Body.User != "root"
  contains(input.Path, "exec")
}

allow {
  input.Method = "GET"
}

allow {
  input.Method == "HEAD"
}

allow {
  contains(input.Path, "resize")
}

allow {
  contains(input.Path, "start")
}
```

**Comment by josephlim75** [comment]
It is working now and I'm closing the issue.  Thanks for your help

**Comment by anderseknert** [comment]
Happy to hear that @josephlim75 👍
