### ISSUE TITLE
Install the plugin on Docker Desktop Windows - WSL2

### ISSUE THREAD

**Issue by voliveirajr** [open-policy-agent/opa-docker-authz#59]
I would like to ask if did you try to install and use the plugin on Docker Desktop for Windows using WSL2 and how to find the right place for the policies file.
On install this mounts a hardcoded path to "/etc/docker" that I believe it's mounted in the "docker-desktop-data" WSL instance, I'm not sure if this instance mount any folder on the Windows host to then, place my policy files.

Any thoughts?

Thank you

**Comment by anderseknert** [comment]
From what I can tell, this location can only be provided when the [plugin is built](https://github.com/open-policy-agent/opa-docker-authz/blob/main/config.json#L23). This kinda makes sense as you need to explicitly allow the plugin to mount that directory, but it certainly offers less in terms of flexibility. I haven't really used WSL2, but could such a directory not be created on the host system?

**Comment by voliveirajr** [comment]
I could figure out where the files are persisted in the WSL instance. Manually creating `\\wsl$\docker-desktop-data\etc\docker` the plugin can mount it during install and it is placed under `\\wsl$\docker-desktop-data\version-pack-data\community\docker\plugins`.

Adding the configuration in the daemon.js it hangs, the logs even in debug didn't give me much details about the issue

These are the logs I could get from runtime and client:
[20:21:42.285][ApiProxy          ][Info   ] msg="error reading response from Docker:  unexpected EOF"
[20:21:42.292][DockerDaemonChecker][Info   ] Docker API is not available yet: Docker daemon query failed: Bad response from Docker engine

----------

[11:03:08.314][IPCServer         ][Info   ] (8d7034c2) cb2be6ea-ServiceAPI S<-C 65219eef-ServiceAPIClient-CSharp POST /dns/refresh-hosts
   at Docker.Core.BackendAPI.ServiceAPIClient.<UpdateHostsAsync>d__5.MoveNext() in C:\workspaces\master-merge\src\github.com\docker\pinata\win\src\Docker.Core\BackendAPI\ServiceAPIClient.cs:line 0
   at Docker.Core.BackendAPI.ServiceAPIClient.UpdateHostsAsync(CancellationToken cancellationToken)
   at Docker.Engines.WSL2.LinuxWSL2Engine.<DoStartAsync>d__28.MoveNext() in C:\workspaces\master-merge\src\github.com\docker\pinata\win\src\Docker.Engines\WSL2\LinuxWSL2Engine.cs:line 104
   at Docker.Engines.WSL2.LinuxWSL2Engine.DoStartAsync(CancellationToken cancellationToken)
   at Docker.ApiServices.StateMachines.StartTransition.<DoRunAsync>d__5.MoveNext() in C:\workspaces\master-merge\src\github.com\docker\pinata\win\src\Docker.ApiServices\StateMachines\StartTransition.cs:line 29
   at Docker.ApiServices.StateMachines.StartTransition.DoRunAsync(CancellationToken cancellationToken)

My guess that is related to TLS, any idea what could I check to troubleshoot this?

**Comment by anderseknert** [comment]
Can't say I've seen that before, no. What exactly did your daemon.json file look like?

**Comment by voliveirajr** [comment]
I built the plugin and pushed to our private registry to be able to install, so the daemon I'm using is 
{
    "authorization-plugins": ["my.private.registry/my-company/openpolicyagent/opa-docker-authz-v2:0.8"]
}

I'm using the same name I get in the docker plugin inspect

**Comment by anderseknert** [comment]
Makes sense that it's reproducible for MacOS, as I think that's the way it normally fails on that platform (authz plugins not currently supported there AFAIK). I don't know why it would fail on Windows though.

**Comment by voliveirajr** [comment]
After a lot of tries I will assume that didn't work yet in WSL2, but not sure exactly why. Starting a new plugin from the scratch using as base the go-plugins-helpers, it worked ok in Docker Desktop 3.6 both for Win(WSL2) and Mac. I guess it's not an issue with the OS or the plugin itself, but with the engine evaluating the policies.
I will close this issue as the project doesn't mention support it anyway.

**Comment by voliveirajr** [comment]
In the future if you want to oficially add support to these environments let me know, I would gladly help you.

**Comment by anderseknert** [comment]
Huh, that's interesting! Thanks for reporting back on that @voliveirajr . The OPA plugin not working in combination with the little I could find on authorization plugins on Mac suggested them not being supported, but if that's not the case that's certainly great news. I'd definitely appreciate your help on adding support for any environment. Do you have code for an example plugin known to work on MacOS?

**Comment by voliveirajr** [comment]
I can't share the plugin but it's not rocket science.
Using the https://github.com/docker/go-plugins-helpers
Or even the ready to use template https://github.com/leogr/docker-authz-plugin
You can write a simple plugin just manipulating the AuthZ object.
You are right, oficially Docker doesn't support plugins in Win and Mac Docker runtimes. However the newer vesions of Docker Desktop runs a docker-ce in a linux virtualization.
As I mentioned before, idk exactly what is preventing OPA to run on these environments, it needs more investigation and understanding of what OPA does but a plugin using the helpers and keeping it simple works fine.

**Comment by anderseknert** [comment]
Thanks @voliveirajr! I guess you're right, it could be a recent change in Docker Desktop. Either way, great! Will definitely look into getting this plugin to run on each platform as soon as I find some time. Thanks for linking to that template, I'll start from there.
