### ISSUE TITLE
OPA plugin not enabled in docker

### ISSUE THREAD

**Issue by meruvavenkatesh** [open-policy-agent/opa-docker-authz#74]
Hi,

I'm trying to install OPA plugin and following Link[https://github.com/open-policy-agent/opa-docker-authz](url).

Getting below error.
<img width="581" alt="image" src="https://github.com/open-policy-agent/opa-docker-authz/assets/29620397/8c6d61e9-7722-41cc-9b25-649491089e77">

Please check.

**Comment by charlieegan3** [comment]
Hi @meruvavenkatesh, I responded to your issue on the OPA repo over here: https://github.com/open-policy-agent/opa/issues/6215

I think this might be better to work out in chat. We have the OPA slack which is the best place to get help with issues like this.

http://slack.openpolicyagent.org
